version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRESS_DB: blog
